version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: pwa_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pwa_test"]
      interval: 3s
      timeout: 3s
      retries: 20
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 20

  prisma-migrator:
    build:
      context: .
      dockerfile: pwa-prisma/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/pwa_test?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: >
      npx prisma migrate deploy

  auth-tests:
    build:
      context: .
      dockerfile: pwa-auth-service/Dockerfile.test
    environment:
      NODE_ENV: test
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/pwa_db?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TELEGRAM_BOT_TOKEN: test_token
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started


  event-handler-tests:
    build:
      context: .
      dockerfile: pwa-event-handler/Dockerfile.test
    environment:
      NODE_ENV: test
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/pwa_db?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TEST_PIXEL_ID: 826333636840272
      TEST_PIXEL_TOKEN: EAAaLM2BeV9oBQbB0JKp9coqezWRqe0FSJ7W3wYbkWNrVTtW3JvZAjdDNGqDS5R1JqLlGUAfwMeyb4kIpQ4b8fnK5ZAUAZAZA1N3Rg1iScZCF6Kl5ZCkRxP8Ux0XuOL8ZC96Xkcn9Djs33cf9mdwbmiIJTnjgf2kR8XZCI5UlxlU8jLZCx3tZAbG8y2wt04ZBnfK7uhSNwZDZD
    depends_on:
      - postgres
      - redis

