global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api_gateway'
    static_configs:
      - targets: ['api-gateway:3000']

  - job_name: 'auth_service'
    static_configs:
      - targets: ['auth-service:4040']

  - job_name: 'event_handler'
    static_configs:
      - targets: ['event-handler:4041']

  - job_name: 'node'
    static_configs:
        - targets: [ 'node-exporter:9100' ]

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]

  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]

