version: "3.9"

services:
  %s:
    image: nginx:1-alpine
    container_name: %s
    volumes:
      - ./:/usr/share/nginx/html:ro
    networks:
     - pwa-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.%f.rule=Host(`%s`)"
      - "traefik.http.routers.%f.entrypoints=web"
      - "traefik.http.services.%f.loadbalancer.server.port=80"
      - "traefik.http.middlewares.pwa-cors.headers.accesscontrolallowmethods=GET,HEAD,OPTIONS"
      - "traefik.http.middlewares.pwa-cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.pwa-cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.pwa-cors.headers.accesscontrolmaxage=600"
      - "traefik.http.middlewares.pwa-cors.headers.addvaryheader=true"
      - "traefik.http.routers.%f.middlewares=pwa-cors@docker"

networks:
  pwa-network:
    external: true