version: "3.9"

services:
  %s:
    image: nginx:1-alpine
    container_name: %s
    volumes:
      - ./:/usr/share/nginx/html:ro
    networks:
     - pwa-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.%f.rule=Host(`%s`)"
      - "traefik.http.routers.%f.entrypoints=web"
      - "traefik.http.services.%f.loadbalancer.server.port=80"

networks:
  pwa-network:
    external: true